### ISSUE TITLE
Reload PCGC FHIR resources using KF base profiles

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-fhir-service#37]
We need to do this as a work around to #35. Update the FHIR mappers to point to the KF base profile (e.g. kfdrc-patient not kfdrc-patient-no-phi) and then re-load the data.

**Comment by liberaliscomputing** [comment]
The following resources have been loaded with the base profiles:

- kfdrc-patients: 2,208
- kfdrc-conditions: 2,629
- kfdrc-phenotypes: 44,531
- kfdrc-specimens: 2,229
