### ISSUE TITLE
Upgrade to new release 2020.05.R01 (Labrador)

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-fhir-service#66]
The new Smile CDR release has a number of improvements, one being snapshot generation. We were told that upgrading to this release may resolve issues #35 and #30.  

- [ ] Run merge_properties.py script to check for settings updates
- [ ] Update master.properties with any new settings
- [ ] Run update_smilecdr.sh script to update container registries
- [ ] Update Dockerfile with new tag
- [ ] Update docker-compose.yml with new tag

**Comment by liberaliscomputing** [comment]
I am closing this ticket due to #87.
