### ISSUE TITLE
Upgrade to new release 2020.08.R03

### ISSUE THREAD

**Issue by liberaliscomputing** [kids-first/kf-api-fhir-service#87]
Referring to [this fresh desk ticket](https://smilecdr.freshdesk.com/support/tickets/409), Smile released a new bug fix for a remote terminology service. It may resolve the following issues:

- d3b-center/clinical-data-flow#74
- kids-first/kf-model-fhir#142
- kids-first/kf-api-fhir-service#32

**Comment by znatty22** [comment]
Has this image been tested to verify the issues are resolved?

**Comment by liberaliscomputing** [comment]
@znatty22, I replied to the fresh desk ticket and this version still has the same problem...

**Comment by liberaliscomputing** [comment]
I am closing this ticket since we recently deployed `2021.05.R5`.
